version: '2'

services:
  reverse_proxy:
    build: ./reverse_proxy
    depends_on:
      - comments_service
      - pyramidal_app_platform
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - reverse_proxy_data:/data
      - personal_site:/public
      - pyramidal_app_front_static:/pyramidal_app_front
    environment:
      TELMMA_FRONT_DOMAIN: 'telmma.online'
      TELMMA_PLATFORM_DOMAIN: 'platform.telmma.online'
      TELMMA_PLATFORM_CONTAINER: 'pyramidal_app_platform'

  # Personal serverd at nicolasoga.com.ar
  personal_site:
    image: nicooga/personal_site
    volumes:
      - personal_site:/personal_site/dist
    environment:
      COMMENTS_API_URL: //comments-service.nicolasoga.com.ar
    env_file:
      - .sensitive/google_keys.env

  # Comments service, served at comments-service.nicolasoga.com.ar
  comments_service:
    image: nicooga/comments_service
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DB_NAME: comments_service_production
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    env_file:
      - .sensitive/google_keys.env

  # Pyramidal APP frontend, served at pyros.nicolasoga.com.ar
  pyramidal_app_front:
    image: pyramidal/front:feature-landing-v2
    depends_on:
      - pyramidal_app_platform
    volumes:
      - pyramidal_app_front_static:/pyramidal_app_front/dist/
    environment:
      PLATFORM_URL: 'https://platform.telmma.online'
      PLATFORM_WS_URL: 'wss://platform.telmma.online/graphql'
    env_file:
      - .sensitive/telmma/front.env

  # Pyramidal APP backend, served at pyramidal-api.nicolasoga.com.ar
  pyramidal_app_platform:
    image: pyramidal/platform
    depends_on:
      - postgres
      - mongo
    ports:
      - '3456:443'
    volumes:
      - reverse_proxy_data:/mnt/reverse_proxy_data
    environment:
      AGENDA_MONGO_DB_URL: mongodb://mongo/agenda
      DB_NAME: pyramidal_app_platform
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    env_file:
      - .sensitive/telmma/platform.env

  mongo:
    image: mongo:3.6.17-xenial
    volumes:
      - mongodata:/data/db

  postgres:
    image: postgres:11.7
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 2112.oga@gmail.com
      PGADMIN_DEFAULT_PASSWORD: asdf2134

volumes:
  personal_site:
  pyramidal_app_front_static:
  pgdata:
  mongodata:
  reverse_proxy_data:
