#!/usr/bin/env sh
docker-compose \
  --tlsverify \
  --tlscacert=".sensitive/telmma/docker_machine_certs/hostinger/ca.pem" \
  --tlscert=".sensitive/telmma/docker_machine_certs/hostinger/cert.pem" \
  --tlskey=".sensitive/telmma/docker_machine_certs/hostinger/key.pem" \
  -H=tcp://93.188.165.215:2376 \
  $@
